// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblEmploymentType
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string? Description { get; set; }
    public int? Status { get; set; }
    public DateTime? DateCreated { get; set; } = DateTime.Now;
    public string? CreatedBy { get; set; }
}