// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_HRIS.Models;

public partial class TblLeaveTypeModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Remarks { get; set; }
    public DateTime DateCreated { get; set; }
    public int CreatedBy { get; set; }
    public bool isDeleted { get; set; }
    public int DeletedBy { get; set; }
    public DateTime DateDeleted { get; set; }
}