// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_HRIS.Models;

public partial class TblOvertimeModel
{
    public int Id { get; set; }
    public string OTNo { get; set; }
    public string EmployeeNo { get; set; }
    public DateTime? Date { get; set; }
    public TimeSpan? StartTime { get; set; }
    public TimeSpan? EndTime { get; set; }
    public decimal? HoursFiled { get; set; }
    public decimal? HoursApproved { get; set; }
    public string Remarks { get; set; }
    public bool? ConvertToLeave { get; set; }
    public string LeaveName { get; set; }
    public string LeaveRemarks { get; set; }
    public string StatusName { get; set; }
    public int? Status { get; set; }
}