// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblPayrollType
{
    public int Id { get; set; }

    public string PayrollType { get; set; }

    public string Description { get; set; }
    public int? DeleteFlag { get; set; }
    public DateTime? DateCreated { get; set; }

    public string CreatedBy { get; set; }
}