// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace API_HRIS.Models;

public partial class TblScheduleModelVM
{
    public int id { get; set; }
    public string title { get; set; }
    public bool isFixed { get; set; }
    public TimeSpan shiftStartTime { get; set; }
    public TimeSpan shiftEndTime { get; set; }
    public TimeSpan breakStartTime { get; set; }
    public TimeSpan breakEndTime { get; set; }
    public DateTime scheduleDate { get; set; }
}