// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace API_HRIS.Models;

public partial class TblTimeSchedule
{
    public int Id { get; set; }
    public int EmploymentTypeId { get; set; }
    public bool isFixed { get; set; }

    [DataType(DataType.Time)]
    public TimeSpan ShiftStartTime { get; set; }

    [DataType(DataType.Time)]
    public TimeSpan ShiftEndTime { get; set; }

    [DataType(DataType.Time)]
    public TimeSpan BreakStartTime { get; set; }

    [DataType(DataType.Time)]
    public TimeSpan BreakEndTime { get; set; }

    [DataType(DataType.Date)]
    public DateTime ScheduleDate { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
}