// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_HRIS.Models;

public partial class UserTypeCountModel
{
    public string? Title { get; set; }

    public int? UserCount { get; set; }
    public int? Total { get; set; }

}