// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;
public partial class loginCredentials
{
    public string? username { get; set; }
    public string? password { get; set; }
    public string? ipaddress { get; set; }
    public string? location { get; set; }
    public string? rememberToken { get; set; }
}