// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;
public partial class TblUsersModel_List
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Fullname { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Mname { get; set; }

    public string Email { get; set; }

    public string Gender { get; set; }

    public string EmployeeId { get; set; }

    public string Jwtoken { get; set; }

    public string FilePath { get; set; }

    public int? Active { get; set; }

    public string Cno { get; set; }

    public string Address { get; set; }

    public int? Status { get; set; }
    public string? StatusName { get; set; }

    public string? DateCreated { get; set; }

    public string? DateUpdated { get; set; }

    public bool DeleteFlag { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string? DateDeleted { get; set; }

    public string DeletedBy { get; set; }

    public string? DateRestored { get; set; }

    public string RestoredBy { get; set; }

    public int? DepartmentId { get; set; }
    public string DepartmentName { get; set; }

    public bool? AgreementStatus { get; set; }

    public string RememberToken { get; set; }
    public string UserType { get; set; }
    public string UserTypeCode { get; set; }
    public string UserTypeName { get; set; }
}