// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using API_HRIS.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace API_HRIS.Models
{
    public partial interface IODC_HRISContextProcedures
    {
        Task<List<GetAllUserDetailsResult>> GetAllUserDetailsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetUserLogInResult>> GetUserLogInAsync(string Username, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_timelogsResult>> sp_timelogsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
