// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models
{
    public partial class sp_timelogsResult
    {
        public int Id { get; set; }
        public int? UserId { get; set; }
        public DateTime? Date { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        [Column("RenderedHours", TypeName = "decimal(18,2)")]
        public decimal? RenderedHours { get; set; }
        public string Username { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Mname { get; set; }
        public string Suffix { get; set; }
        public string Email { get; set; }
        public string EmployeeID { get; set; }
        public string JWToken { get; set; }
        public string FilePath { get; set; }
        public int? UsertypeId { get; set; }
        public string UserType { get; set; }
        public string StatusName { get; set; }
        public int? StatusId { get; set; }
        public string Remarks { get; set; }
        public string Task { get; set; }
    }
}
