// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblAddressInfo
{
    public int Id { get; set; }

    public string CountryOfBirth { get; set; }

    public string Region { get; set; }

    public string Province { get; set; }

    public string Municipality { get; set; }

    public string Barangay { get; set; }

    public int? UserId { get; set; }

    public int? Status { get; set; }

    public DateTime? DateCreated { get; set; }
}