// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblLeaveLedgerModel
{
    public int Id { get; set; }
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string LeaveCode { get; set; }
    public int UserId { get; set; }
    public int LeaveId { get; set; }
    public decimal Earned { get; set; }
    public decimal Consumed { get; set; }
    public decimal Balance { get; set; }
    public DateTime? ExpirationDate { get; set; }
    [DataType(DataType.Date)]
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string Source { get; set; }
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string Remarks { get; set; }
    public DateTime DateCreated { get; set; }
    public int CreatedBy { get; set; }
    public bool isDeleted { get; set; }
    public int DeletedBy { get; set; }
    public DateTime DateDeleted { get; set; }
}