// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblModulesModel
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Img { get; set; }

    public string Link { get; set; }

    public string Class { get; set; }

    public int? Status { get; set; }
}