// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_HRIS.Models;

public partial class TblOvertimeModel
{
    public int Id { get; set; }
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string OTNo { get; set; }
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string EmployeeNo { get; set; }
    public DateTime? Date { get; set; }
    [DataType(DataType.Time)]
    public TimeSpan? StartTime { get; set; }
    [DataType(DataType.Time)]
    public TimeSpan? EndTime { get; set; }
    [DataType(DataType.Date)]
    public DateTime? StartDate { get; set; }
    [DataType(DataType.Date)]
    public DateTime? EndDate { get; set; }
    public decimal? HoursFiled { get; set; }
    public decimal? HoursApproved { get; set; }
    [Column(TypeName = "varchar(255)")]
    [MaxLength(255)]
    public string? Remarks { get; set; }
    public bool? ConvertToLeave { get; set; }
    public DateTime? DateCreated { get; set; }
    public int? LeaveId { get; set; }
    public int? Status { get; set; }
    public int? CreatedBy { get; set; }
    public bool? isDeleted { get; set; }
    public int? DeletedBy { get; set; }
    public DateTime? DateDeleted { get; set; }
}