// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_HRIS.Models;

public partial class TblTaskModel
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string TaskDescription { get; set; }

    public DateTime? DateCreated { get; set; }

    public DateTime? DateUpdated { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public int? Status { get; set; }

    public int? HoursofWork { get; set; }
    public int? isBreak { get; set; }
}